---
language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - jruby-18mode
  - jruby-19mode
  - rbx-19mode

bundler_args: --path vendor/bundle

before_install:
  - sudo apt-get install rpm

script:
  - bundle exec rake test:all
